language: python
python:
- '2.7'
install:
- pip install cx_Oracle
script:
- python test.py
after_script:
- if test $TRAVIS_BRANCH = "master";then JOB=$JOB_PROD;elif test $TRAVIS_BRANCH =
  "test";then JOB=$JOB_TEST;elif test $TRAVIS_BRANCH = "fix-ci";then JOB=$JOB_TEST;fi
- if test ! -z $JOB;then curl -X POST --data "authtoken=$AUTH_TOKEN&argString=-checkout-reference
  $TRAVIS_COMMIT" https://melinda-ci.lib.helsinki.fi/api/14/job/$JOB/executions;fi
env:
  global:
  - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
  - JOB_PROD=638b36b9-709e-4625-bcd4-2029ff2bef58
  - JOB_TEST=1815b0f8-44dd-4011-a394-3afc61b05bff
  - secure: be4Ord5gi9w2w4aF3/AZDyg02vuhBK/KSO6ghpn5+taH8VBnK5rd6yrMoUrEEChHpCcUjgAQD/ky44RwNOuzqDSFlgwuO+Oor9+3SVfxuBinR9YmHAUR8n5afrx4ygsjogTMfxTCMKps4seyBUwIaXXWDq5G4S7XfKpuzzLvSPaq+/ocyM0LmbT0HfHAi3mLI5vsUd0tMb/OnXF/5RkvubhfslF2YI3OxLXX6x2wEyx8CO8PQELXRMgA0sXod8V9zYopC5J3J7tuDf3UCrQRBHFj44weiVWWU7W0wYWzKzeOxNv4BaxpJu4iDlQL/RMvx4VkqK7JDroIBcXjGvYtzN3mBknHjvkiK+5jm+WVmPaciKJMq4NJyNlxIxUgsCIeX1vasdWBs0BF4hJQFvKyket7x4n5MKpiVYhWZ24z9wjObSrcTQL1NKldPPiYBYOiAvfhEJ4w/xn7rus/PzfopE+WWX5Y7wYlYVCxT5K4lGx9wYxXDaxnMwq78w7MqLSATg/DOgtiHohyseWfPoutVaNQv+PfmejbsznAeoK39+e7x/J1C2VCP5H0S9P51Il2Nmv0iMHZuAbYLiswKXgxqC1kQYUSyCWyvdGvNPpcDC948OjMdmxrgOPQ8LaQTDhvMoresa+W2W5qW1tnEqivFikm1Xb0EfAB9DbSDS7TUzA=
