language: python
python:
- '2.7'
install:
- pip install cx_Oracle
script:
- python test.py
after_script:
- if test $TRAVIS_BRANCH = "master";then JOB=$JOB_PROD;elif test $TRAVIS_BRANCH =
  "test";then JOB=$JOB_TEST;elif test $TRAVIS_BRANCH = "fix-ci";then JOB=$JOB_TEST;fi
- if test ! -z $JOB;then curl -X POST --data "authtoken=$AUTH_TOKEN&argString=-checkout-reference
  $TRAVIS_COMMIT" https://melinda-ci.lib.helsinki.fi/api/14/job/$JOB/executions;fi
env:
  global:
  - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
  - JOB_PROD=638b36b9-709e-4625-bcd4-2029ff2bef58
  - JOB_TEST=1815b0f8-44dd-4011-a394-3afc61b05bff
  - secure: oRmXBy2L4J6Y2QirBPCw+baCBOStTFs5FjrQow5AortWRUWf54lId16whisrE/vQw1yYWdShfjGUcInpFQ1p0lW56h99wHL8uAXFvDJOPMm4x0JjmmTvuP/x77CPeOPEn+0dcaZ4Dehq/AkOzdXztNk+isq8Dq//24+ROlV5FFlG26uZvdBuZImR17BPSZ7LdOVUvHMe+3E2ADobvJH2TIH+lqVyr+fuMRXkoq+O+zcVYYDh/aucmcpE845Jw02SfNifpw/DxHc6aHljvM2oLWSg6i4UC3p7Hh6QYCPSqYiEyNG6f4pa9D6A2oQrq6EnYn8E4G6MR4nLyrl7giQVZef4Q27JjM95yeDVCMfXGRoFHBL65jkrWILKzbmHxmvzDqqpAkXscNUjXwbtJz6PbBQ1hOYrvELh6T/Jx1QpQfPGHswFYC0lsB/dj6F/hYgIQWGmn3IWbQvvt6q0z3PvC8lDOsqcWyR956yGHPa9NKLzrYwuC1zVbNsMqSScwWwsuHA6p5imgJH2AY4MK7QEs/4xLwcBwvuU4cMSAIO6LnBfEjlpx9LZ4C2um7qMS6LgEbcupG35nathn6aILtbV77/tuDFxIcPj0Wi2qh2AKZA0j7TeOMxfoCzJi1VviJEclIB3dB6Y8s5utHMezoRg8k7+3EvSwxTMFsJwkLA59zQ=
